### ISSUE TITLE
regenerate index

### ISSUE THREAD

**Issue by wanderer** [drom/wast-codegen#12]
the `index.js` needs to be regenerated and the package bumped because we updated wast-spec after 0.3.1 was published 

i was totally stuck on this on for awhile. codegen installed from npm didn't work, but if i cloned codegen and `link`ed it, it would work. It didn't dawn on me till i did a diff on the index.js's

**Comment by drom** [comment]
@wanderer when you install package `npm i wast-codegen` it runs `prepublish` script and will generate `index.js`. Or! you can run `npm i` inside `wast-codegen` clone the do the same thing.

**Comment by wanderer** [comment]
@drom hmm so just installed from npm. And I did a `diff` from the index i generated from git clone and I get this. 
```
76,78d75
<         if (node.id) {
<             exprGen[node.id.kind](node.id);
<         }
121c118
<         node.body.forEach(function (e) {
---
>         node.exprs.forEach(function (e) {
124c121
<         node.exprs.forEach(function (e) {
---
>         node.body.forEach(function (e) {
231,233d227
<         node.local.forEach(function (e) {
<             exprGen[e.kind](e);
<         });
```

What could cause the discrepancy?

**Comment by wanderer** [comment]
@drom this is still an issue for me. I think prepublish isn't doing exactly what you think it is https://blog.greenkeeper.io/what-is-npm-s-prepublish-and-why-is-it-so-confusing-a948373e6be1#.bvm6kil78

**Comment by drom** [comment]
@wanderer have you pulled latest `wast-codegen` from upstream?

**Comment by wanderer** [comment]
yeah it works fine when installed from git. But doesn't work when installed form npm as a dependency. When it is installed by as dependency the outdated index.js is used.

**Comment by drom** [comment]
@wanderer are you changing code inside of `node_modules` ?

**Comment by wanderer** [comment]
@drom nope

**Comment by wanderer** [comment]
you can see wast-codegen fail to produce the correct s-expressions here https://travis-ci.org/wanderer/wasm-metering/jobs/122682721

Those tests will work fine; but I have to manually regenerate the index.js

**Comment by drom** [comment]
@wanderer I have rebuild and published new version.

**Comment by wanderer** [comment]
@drom awesome works now!
