### ISSUE TITLE
export memory not working

### ISSUE THREAD

**Issue by axic** [drom/wast-codegen#18]
Input:
```
(export "memory" memory)
```

JSON:
```
{"kind":"export","name":{"kind":"literal","value":"memory"},"id":{"kind":"literal","value":"memory"}}
```

Output:
```
(export "memory" "memory")
```

The `id` probably should be a special `identifier` (without the `$` sign) and not a `literal` - this maybe an issue with `wast-parser` in that case.

**Comment by drom** [comment]
@axic Thank you for reporting all issues.

**Comment by axic** [comment]
@drom thank's for fixing them 😃 

I'm actually patching output generated via `clang` and that turns out to be a good stress test for parser and codegen.

**Comment by drom** [comment]
@axic yes, looks like issue with `literal` type in parser. Second `memory` is not `String Literal` nor `$ Identifier`, it is something else, not provisioned in AST.
