### ISSUE TITLE
size modifiers of load/store operations are ignored

### ISSUE THREAD

**Issue by axic** [drom/wast-codegen#23]
Input:
```
  (func
    (i32.load8 (i32.const 0))
  )
```

JSON:
```
{"kind":"load","type":"i32","size":8,"sign":null,"offset":0,"align":0,"expr":{"kind":"const","type":"i32","init":"0"}}
```

Output:
```
  (func
    (i32.load 
      (i32.const 0))))
```

The `size` field seems to be present. The following definitely fail:
- i32.store8
- i32.load8_u
- i32.load8_s
- i32.load16_u
- i32.load16_s
- i64.load16

Probably all of them fail, but didn't had time to test.

**Comment by drom** [comment]
fixed with https://github.com/drom/wast-codegen/commit/694b334b3e65feb28b94b6c83a57c919a830d85f

**Comment by axic** [comment]
Thank you! With this I am finally able to run my clang-compiled sha256 after transforming it via wast-parser/codegen. Great job!
