### ISSUE TITLE
codegen generator

### ISSUE THREAD

**Issue by drom** [drom/wast-codegen#7]
The `codegen` code looks flat, boring and repetitive. I has to be so for high performance.
But, I am wondering about the possibility of generating this `exprGen` object from small set of rules and exceptions.

Node function rules (low to high priority):
  1. it puts `(..)` around what ever it generates.
  2. list of exceptions like: 'literal, literal, item,...`;
  3. it adds its `kind` into output stream. `nop -> (nop ...)`
  4. `kind` exception table lists the node functions that construct name from multiple fields, like: `binop, cvtop, relop, unop,...`
  5. `VisitorKeys` table similar to https://github.com/drom/wast-traverse/blob/master/index.js will direct the order of inner elements. We will need to put more information to distinguish `Object` vs `Array`

As a build step: the generator code can generate Mozilla AST of `codegen` and then we can use `escodegen` to produce desired JS file.

@wanderer what do you think?

**Comment by wanderer** [comment]
thats sounds like a very intersting idea!

**Comment by wanderer** [comment]
could something like VisitorKeys go in wast-spec? I also use that here https://github.com/wanderer/wast-graph/blob/master/index.js#L4-L49 so it might be nice to have it a central place

**Comment by drom** [comment]
Yes, this structure (but maybe in modified form) belong to the spec.

**Comment by drom** [comment]
Added issue here: https://github.com/drom/wast-spec/issues/12

**Comment by drom** [comment]
very ugly first draft of generator.
